[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  environment = {
    NODE_VERSION = "18",
    PNPM_VERSION = "8.x.x" # Or the specific version your project uses, e.g., "8.15.6"
  }
