# Netlify configuration for the EngageNatural Vite React App

# Build settings for Netlify.
[build]
  # Simple build command:
  # 1. Use Netlify-recommended npx approach to ensure pnpm is available
  # 2. Install dependencies (allows updating lockfile if needed)
  # 3. Run the production build
  command = "npx pnpm install --no-frozen-lockfile && npx pnpm run build"
  
  # The directory that contains the built site. Vite's default is "dist".
  publish = "dist"

  # Environment variables needed for the build process.
[build.environment]
    NODE_VERSION = "18.20.8"

# Redirect rule for Single Page Applications (SPAs).
# This ensures that all routes are handled by index.html, allowing
# client-side routing (like React Router) to work correctly.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
