# Netlify configuration for the EngageNatural Vite React App

# Build settings for Netlify.
[build]
  # Robust build command:
  # 1. Install pnpm globally (if not already installed)
  # 2. Remove any existing lockfile to avoid mismatch errors
  # 3. Install dependencies (generates a fresh lockfile)
  # 4. Run the production build
  command = "npm i -g pnpm && rm -f pnpm-lock.yaml && pnpm install && node netlify-setup.js && pnpm run build"
  
  # The directory that contains the built site. Vite's default is "dist".
  publish = "dist"

  # Environment variables needed for the build process.
[build.environment]
    NODE_VERSION = "18.20.8"

# Redirect rule for Single Page Applications (SPAs).
# This ensures that all routes are handled by index.html, allowing
# client-side routing (like React Router) to work correctly.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
